const ADMIN_KEY = "shop-admin-7f4c2a91";

const HTML = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Reflex Shop</title><script src="https://telegram.org/js/telegram-web-app.js"></script><style>
:root{--bg:#07111d;--card:rgba(19,31,48,.78);--line:rgba(255,255,255,.09);--text:#f4f7fb;--muted:#8fa0b5;--a:#16d7c4;--b:#5b67ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 10% 0,#123b45 0,transparent 35%),radial-gradient(circle at 90% 10%,#27204f 0,transparent 38%),var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,sans-serif}button,input{font:inherit}button{border:0}.wrap{max-width:720px;margin:auto;padding:18px 14px 90px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.brand{font-size:22px;font-weight:800}.pill{padding:8px 12px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.05);color:var(--muted)}.hero{padding:22px;border-radius:26px;background:linear-gradient(135deg,rgba(22,215,196,.18),rgba(91,103,255,.2));border:1px solid var(--line);margin-bottom:16px}.hero h1{margin:0 0 8px;font-size:30px}.hero p{margin:0;color:var(--muted)}.search{width:100%;padding:14px 16px;border-radius:17px;border:1px solid var(--line);background:rgba(255,255,255,.05);color:white;outline:none;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:14px;backdrop-filter:blur(18px)}.emoji{height:110px;border-radius:15px;background:linear-gradient(135deg,rgba(22,215,196,.18),rgba(91,103,255,.2));display:grid;place-items:center;font-size:46px;margin-bottom:12px}.name{font-weight:750;min-height:42px}.meta{font-size:13px;color:var(--muted);margin:6px 0 10px}.price{font-size:19px;font-weight:800;margin-bottom:10px}.btn{width:100%;padding:12px;border-radius:14px;background:linear-gradient(90deg,var(--a),var(--b));color:white;font-weight:800}.nav{position:fixed;bottom:10px;left:50%;transform:translateX(-50%);width:min(690px,calc(100% - 20px));display:grid;grid-template-columns:repeat(4,1fr);gap:6px;padding:8px;border:1px solid var(--line);background:rgba(7,17,29,.88);backdrop-filter:blur(20px);border-radius:20px}.nav button{background:transparent;color:var(--muted);padding:8px 2px;border-radius:12px}.nav button.active{color:white;background:rgba(255,255,255,.08)}.section{margin-top:18px}.row{display:flex;justify-content:space-between;gap:10px;align-items:center}.list{display:grid;gap:10px}.item{padding:14px;border:1px solid var(--line);border-radius:17px;background:rgba(255,255,255,.04)}.empty{text-align:center;color:var(--muted);padding:40px 10px}.admin input,.admin textarea{width:100%;padding:12px;border-radius:12px;border:1px solid var(--line);background:#0b1725;color:white;margin:5px 0}.admin .btn{margin-top:8px}.stats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.stat{padding:15px;border-radius:17px;border:1px solid var(--line);background:rgba(255,255,255,.04)}.stat b{font-size:23px}.danger{background:#8b2e45}.small{font-size:12px;color:var(--muted)}@media(min-width:600px){.grid{grid-template-columns:repeat(3,1fr)}}
</style></head><body><div id="app"></div><script>
const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
let products=[],cart=JSON.parse(localStorage.getItem('cart')||'{}'),orders=[],page='shop',admin=false;
const api=async(u,o)=>{const r=await fetch(u,o);return r.json()};
function money(n){return new Intl.NumberFormat('ru-RU').format(n)+' ₽'}
async function load(){try{products=await api('/api/products')}catch(e){products=[]}render()}
function add(id){cart[id]=(cart[id]||0)+1;localStorage.setItem('cart',JSON.stringify(cart));render()}
function total(){return products.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0)}
function render(){const a=document.getElementById('app');if(page==='admin'){renderAdmin(a);return}let q='';let visible=products;if(page==='shop'){q='<input class="search" placeholder="Поиск товара" oninput="filter(this.value)">';}if(page==='cart'){const rows=products.filter(p=>cart[p.id]);q='<div class="section"><h2>Корзина</h2><div class="list">'+(rows.length?rows.map(p=>\`<div class=item><div class=row><b>\${p.name}</b><b>\${money(p.price*(cart[p.id]||0))}</b></div><div class=small>\${cart[p.id]} × \${money(p.price)}</div></div>\`).join(''):'<div class=empty>Корзина пуста</div>')+'</div>'+(rows.length?\`<div class=item style="margin-top:12px"><div class=row><b>Итого</b><b>\${money(total())}</b></div><button class=btn onclick="checkout()">Оформить заказ</button></div>\`:'');}
if(page==='orders'){q='<div class=section><h2>Мои заказы</h2><div id=ordersbox class=list><div class=empty>Загрузка...</div></div></div>';setTimeout(loadOrders,0)}
if(page==='profile'){q='<div class=section><h2>Профиль</h2><div class=item><b>'+((tg?.initDataUnsafe?.user?.first_name)||'Покупатель')+'</b><p class=small>Telegram Mini App</p></div><div class=item style="margin-top:10px"><button class=btn onclick="openAdmin()">Админка</button></div></div>'}
if(page==='shop')q+=\`<div class=grid id=grid>\${visible.map(card).join('')}</div>\`;
a.innerHTML=\`<div class=wrap><div class=top><div class=brand>REFLEX SHOP</div><div class=pill>\${Object.values(cart).reduce((a,b)=>a+b,0)} шт.</div></div>\${page==='shop'?'<div class=hero><h1>Магазин</h1><p>Каталог, корзина и заказы прямо в Telegram.</p></div>':''}\${q}</div><div class=nav><button class="\${page==='shop'?'active':''}" onclick="go('shop')">🏠<br>Каталог</button><button class="\${page==='cart'?'active':''}" onclick="go('cart')">🛒<br>Корзина</button><button class="\${page==='orders'?'active':''}" onclick="go('orders')">📦<br>Заказы</button><button class="\${page==='profile'?'active':''}" onclick="go('profile')">👤<br>Профиль</button></div>\`}
function card(p){return \`<div class=card><div class=emoji>\${p.emoji||'🛍️'}</div><div class=name>\${p.name}</div><div class=meta>Остаток: \${p.stock}</div><div class=price>\${money(p.price)}</div><button class=btn onclick="add(\${p.id})">В корзину</button></div>\`}
function filter(v){const g=document.getElementById('grid');g.innerHTML=products.filter(p=>p.name.toLowerCase().includes(v.toLowerCase())).map(card).join('')}
function go(p){page=p;render()}
async function checkout(){const items=products.filter(p=>cart[p.id]).map(p=>({product_id:p.id,qty:cart[p.id]}));if(!items.length)return;const r=await api('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items,user:tg?.initDataUnsafe?.user||{}})});if(r.ok){cart={};localStorage.removeItem('cart');alert('Заказ оформлен');go('orders')}else alert(r.error||'Не удалось оформить заказ')}
async function loadOrders(){const u=encodeURIComponent(tg?.initDataUnsafe?.user?.id||'guest');const r=await api('/api/orders?user='+u);const box=document.getElementById('ordersbox');box.innerHTML=r.length?r.map(o=>\`<div class=item><div class=row><b>Заказ #\${o.id}</b><b>\${money(o.total)}</b></div><div class=small>\${o.status}</div></div>\`).join(''):'<div class=empty>Заказов пока нет</div>'}
function openAdmin(){const k=prompt('Введите ключ администратора');if(k===ADMIN_KEY){admin=true;page='admin';render()}else if(k)alert('Неверный ключ')}
function renderAdmin(a){if(!admin){page='profile';render();return}a.innerHTML='<div class="wrap admin"><div class="top"><div class="brand">Админка</div><button class="pill" onclick="go(\'shop\')">Магазин</button></div><div class="stats" id="stats">Загрузка...</div><div class="section"><h3>Добавить товар</h3><input id="n" placeholder="Название"><input id="p" type="number" min="0" placeholder="Цена"><input id="c" type="number" min="0" placeholder="Себестоимость"><input id="s" type="number" min="0" placeholder="Остаток"><input id="e" placeholder="Эмодзи" value="🛍️"><textarea id="d" placeholder="Описание"></textarea><button class="btn" onclick="createProduct()">Добавить товар</button></div><div class="section"><h3>Товары</h3><div id="plist" class="list"></div></div><div class="section"><h3>Заказы</h3><div id="olist" class="list"><div class="empty">Загрузка...</div></div></div></div>';loadAdmin()}
async function loadAdmin(){const s=await api('/api/admin/stats?key='+ADMIN_KEY);document.getElementById('stats').innerHTML='<div class="stat"><span class="small">Выручка</span><br><b>'+money(s.revenue)+'</b></div><div class="stat"><span class="small">Прибыль</span><br><b>'+money(s.profit)+'</b></div><div class="stat"><span class="small">Заказы</span><br><b>'+s.orders+'</b></div><div class="stat"><span class="small">Клиенты</span><br><b>'+s.customers+'</b></div><div class="stat"><span class="small">Товаров</span><br><b>'+s.products+'</b></div><div class="stat"><span class="small">В работе</span><br><b>'+s.in_work+'</b></div>';const ps=await api('/api/admin/products?key='+ADMIN_KEY);document.getElementById('plist').innerHTML=ps.length?ps.map(p=>'<div class="item"><div class="row"><b>'+esc(p.name)+'</b><b>'+money(p.price)+'</b></div><div class="small">Остаток: '+p.stock+' · Себестоимость: '+money(p.cost||0)+'</div><div class="row" style="margin-top:8px"><button class="btn" onclick="editProduct('+p.id+')">Изменить</button><button class="btn danger" onclick="deleteProduct('+p.id+')">Удалить</button></div></div>').join(''):'<div class="empty">Товаров пока нет</div>';const os=await api('/api/admin/orders?key='+ADMIN_KEY);document.getElementById('olist').innerHTML=os.length?os.map(o=>'<div class="item"><div class="row"><b>Заказ #'+o.id+'</b><b>'+money(o.total)+'</b></div><div class="small">'+esc(o.customer||'Покупатель')+' · '+(o.created_at||'')+'</div><select onchange="setOrderStatus('+o.id+',this.value)" style="width:100%;margin-top:8px;padding:10px;border-radius:10px;background:#0b1725;color:white;border:1px solid var(--line)">'+['Новый','В работе','Доставлен','Отменён'].map(x=>'<option '+(o.status===x?'selected':'')+'>'+x+'</option>').join('')+'</select></div>').join(''):'<div class="empty">Заказов пока нет</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function createProduct(){const body={name:n.value.trim(),price:+p.value,cost:+c.value||0,stock:+s.value||0,emoji:e.value||'🛍️',description:d.value||''};const r=await api('/api/admin/products?key='+ADMIN_KEY,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.ok){alert('Товар добавлен');n.value='';p.value='';c.value='';s.value='';d.value='';e.value='🛍️';loadAdmin();load()}else alert(r.error||'Ошибка')}
async function editProduct(id){const p0=await api('/api/admin/products/'+id+'?key='+ADMIN_KEY);if(!p0.id)return alert('Товар не найден');const name=prompt('Название',p0.name);if(name===null)return;const price=prompt('Цена',p0.price);if(price===null)return;const cost=prompt('Себестоимость',p0.cost||0);if(cost===null)return;const stock=prompt('Остаток',p0.stock);if(stock===null)return;const r=await api('/api/admin/products/'+id+'?key='+ADMIN_KEY,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({name,price:+price,cost:+cost,stock:+stock,emoji:p0.emoji,description:p0.description})});if(r.ok){loadAdmin();load()}else alert(r.error||'Ошибка')}
async function deleteProduct(id){if(!confirm('Удалить товар?'))return;const r=await api('/api/admin/products/'+id+'?key='+ADMIN_KEY,{method:'DELETE'});if(r.ok){loadAdmin();load()}else alert(r.error||'Ошибка')}
async function setOrderStatus(id,status){const r=await api('/api/admin/orders/'+id+'?key='+ADMIN_KEY,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({status})});if(!r.ok)alert(r.error||'Ошибка')}
load();
</script></body></html>`;

const schema=`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT DEFAULT '',price INTEGER NOT NULL,cost INTEGER NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,emoji TEXT DEFAULT '🛍️',active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,tg_user_id TEXT,tg_username TEXT,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'Новый',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,qty INTEGER,price INTEGER);`;
async function ensure(env){if(!env.DB)return;try{await env.DB.prepare('ALTER TABLE products ADD COLUMN cost INTEGER NOT NULL DEFAULT 0').run()}catch(e){}try{await env.DB.prepare('SELECT 1 FROM products LIMIT 1').first()}catch(e){for(const q of schema.split(';').filter(Boolean))await env.DB.prepare(q).run();const n=await env.DB.prepare('SELECT COUNT(*) c FROM products').first();if(!n.c){await env.DB.prepare('INSERT INTO products(name,description,price,stock,emoji) VALUES(?,?,?,?,?)').bind('Пример товара','Замените через админку',450,10,'🛍️').run();}}}
async function json(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*'}})}
export default {async fetch(request,env){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response('',{headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'}});if(env.DB)await ensure(env);if(u.pathname==='/api/products')return json(env.DB?await env.DB.prepare('SELECT * FROM products WHERE active=1 ORDER BY id DESC').all().then(x=>x.results):[]);if(u.pathname==='/api/orders'&&request.method==='GET'){const user=u.searchParams.get('user')||'guest';return json(env.DB?await env.DB.prepare('SELECT * FROM orders WHERE tg_user_id=? ORDER BY id DESC').bind(user).all().then(x=>x.results):[])}if(u.pathname==='/api/orders'&&request.method==='POST'){if(!env.DB)return json({error:'D1 не подключена'},500);const b=await request.json();let total=0;const items=[];for(const it of b.items||[]){const p=await env.DB.prepare('SELECT * FROM products WHERE id=? AND active=1').bind(it.product_id).first();if(!p||p.stock<it.qty)return json({error:'Недостаточно товара'},400);total+=p.price*it.qty;items.push({p,qty:it.qty})}const user=b.user||{};const r=await env.DB.prepare('INSERT INTO orders(tg_user_id,tg_username,total) VALUES(?,?,?)').bind(String(user.id||'guest'),user.username||'',total).run();for(const x of items){await env.DB.prepare('INSERT INTO order_items(order_id,product_id,qty,price) VALUES(?,?,?,?)').bind(r.meta.last_row_id,x.p.id,x.qty,x.p.price).run();await env.DB.prepare('UPDATE products SET stock=stock-? WHERE id=?').bind(x.qty,x.p.id).run()}return json({ok:true,id:r.meta.last_row_id})}if(u.pathname==='/api/admin/stats'){if(u.searchParams.get('key')!==ADMIN_KEY)return json({error:'forbidden'},403);const rev=await env.DB.prepare("SELECT COALESCE(SUM(total),0) revenue,COUNT(*) orders,COUNT(DISTINCT tg_user_id) customers FROM orders").first();const profit=await env.DB.prepare("SELECT COALESCE(SUM(oi.qty*(oi.price-p.cost)),0) profit FROM order_items oi JOIN products p ON p.id=oi.product_id JOIN orders o ON o.id=oi.order_id WHERE o.status!='Отменён'").first();const pc=await env.DB.prepare('SELECT COUNT(*) products FROM products WHERE active=1').first();const iw=await env.DB.prepare("SELECT COUNT(*) in_work FROM orders WHERE status='В работе'").first();return json({...rev,...profit,...pc,...iw})}
if(u.pathname==='/api/admin/products'&&request.method==='GET'){if(u.searchParams.get('key')!==ADMIN_KEY)return json({error:'forbidden'},403);return json((await env.DB.prepare('SELECT * FROM products ORDER BY id DESC').all()).results)}
if(u.pathname==='/api/admin/products'&&request.method==='POST'){if(u.searchParams.get('key')!==ADMIN_KEY)return json({error:'forbidden'},403);const b=await request.json();if(!b.name||!Number.isFinite(+b.price))return json({error:'Заполни название и цену'},400);await env.DB.prepare('INSERT INTO products(name,description,price,cost,stock,emoji) VALUES(?,?,?,?,?,?)').bind(b.name,b.description||'',+b.price,+b.cost||0,+b.stock||0,b.emoji||'🛍️').run();return json({ok:true})}
const pm=u.pathname.match(/^\/api\/admin\/products\/(\d+)$/);if(pm){if(u.searchParams.get('key')!==ADMIN_KEY)return json({error:'forbidden'},403);const id=+pm[1];if(request.method==='GET'){const p=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first();return json(p||{},p?200:404)}if(request.method==='PUT'){const b=await request.json();await env.DB.prepare('UPDATE products SET name=?,description=?,price=?,cost=?,stock=?,emoji=? WHERE id=?').bind(b.name,b.description||'',+b.price,+b.cost||0,+b.stock||0,b.emoji||'🛍️',id).run();return json({ok:true})}if(request.method==='DELETE'){await env.DB.prepare('UPDATE products SET active=0 WHERE id=?').bind(id).run();return json({ok:true})}}
if(u.pathname==='/api/admin/orders'&&request.method==='GET'){if(u.searchParams.get('key')!==ADMIN_KEY)return json({error:'forbidden'},403);const r=await env.DB.prepare("SELECT o.*, COALESCE(o.tg_username,o.tg_user_id,'Покупатель') customer FROM orders o ORDER BY o.id DESC").all();return json(r.results)}
const om=u.pathname.match(/^\/api\/admin\/orders\/(\d+)$/);if(om&&request.method==='PUT'){if(u.searchParams.get('key')!==ADMIN_KEY)return json({error:'forbidden'},403);const b=await request.json();const allowed=['Новый','В работе','Доставлен','Отменён'];if(!allowed.includes(b.status))return json({error:'Недопустимый статус'},400);await env.DB.prepare('UPDATE orders SET status=? WHERE id=?').bind(b.status,+om[1]).run();return json({ok:true})}
if(u.pathname==='/api/schema')return new Response(schema,{headers:{'content-type':'text/plain'}});return new Response(HTML,{headers:{'content-type':'text/html; charset=utf-8'}})}};
